alias py='python3'
alias python='python3'

alias update='sudo apt update'
alias upgrade='sudo apt upgrade'

alias install='sudo apt install'
alias add='sudo apt install'
alias remove='sudo apt remove'
alias purge='sudo apt purge'
alias search='sudo apt search'


alias j='django-admin'
alias admin='django-admin'
alias g='python3 manage.py'
alias runserver='python3 manage.py runserver'
alias runs='python3 manage.py runserver'
alias server='python3 manage.py runserver'
alias serve='python3 manage.py runserver'

alias activate='cd && . env/bin/activate && cd -'
alias activat='cd && . env/bin/activate && cd -'
alias active='cd && . env/bin/activate && cd -'
alias activ='cd && . env/bin/activate && cd -'
alias act='cd && . env/bin/activate && cd -'
alias ac='cd && . env/bin/activate && cd -'
alias deactive='deactivate'
alias deactiv='deactivate'
alias deact='deactivate'
alias deac='deactivate'
alias dc='deactivate'

alias pip='ac && pip'
alias pipinstall='ac && pip install'
alias pin='ac && pip install'
alias pins='ac && pip install'

alias p='cd -' ## pd
alias pd='cd -' ## pd
alias ..='cd ..'
alias ...='cd ../../'

alias g='git'
alias i='git init'
alias gi='git init'
alias ini='git init'
alias init='git init'
alias a='git add'
alias ga='git add'
alias ad='git add'
alias adl='git add .'
alias adal='git add .'
alias adall='git add .'
alias addall='git add .'
alias s='git status'
alias gs='git status'
alias gits='git status'
alias c='git commit'
alias gc='git commit'
alias cm='git commit -m'
alias comit='git commit'
alias commit='git commit'
alias comitm='git commit -m'
alias commitm='git commit -m'
alias pl='git pull'
alias gpl='git pull'
alias pul='git pull'
alias pull='git pull'
alias ps='git push'
alias gps='git push'
alias push='git push'
