alias py='python3'
alias python='python3'

alias update='sudo apt update'
alias upgrade='sudo apt upgrade'

alias install='sudo apt install'
alias add='sudo apt install'
alias remove='sudo apt remove'
alias purge='sudo apt purge'
alias search='sudo apt search'


alias django='django-admin'
alias admin='django-admin'
alias manage='python3 manage.py'
alias manag='python3 manage.py'
alias runserver='python3 manage.py runserver'
alias run='python3 manage.py runserver'
alias runs='python3 manage.py runserver'
alias server='python3 manage.py runserver'
alias serve='python3 manage.py runserver'
alias serv='python3 manage.py runserver'

alias activate='cd && . env/bin/activate && cd -'
alias activat='cd && . env/bin/activate && cd -'
alias active='cd && . env/bin/activate && cd -'
alias activ='cd && . env/bin/activate && cd -'
alias act='cd && . env/bin/activate && cd -'
alias ac='cd && . env/bin/activate && cd -'
alias deactive='deactivate'
alias deactiv='deactivate'
alias deact='deactivate'
alias deac='deactivate'
alias dc='deactivate'

alias pip='ac && pip'
alias pipinstall='ac && pip install'
alias pi='ac && pip install'
alias pin='ac && pip install'
alias pins='ac && pip install'

alias pd='cd -' ## pd
alias ..='cd ..'
alias ...='cd ../../'

alias gi='git init'
alias ga='git add'
alias gad='git add'
alias gadl='git add .'
alias gadal='git add .'
alias gadall='git add .'
alias gaddall='git add .'
alias gits='git status'
alias gs='git status'
alias gc='git commit'
alias gcm='git commit -m'
alias gcomit='git commit'
alias gcommit='git commit'
alias gcomitm='git commit -m'
alias gcommitm='git commit -m'
alias gpl='git pull'
alias gpul='git pull'
alias gpull='git pull'
alias gps='git push'
alias gpush='git push'
